### ISSUE TITLE
模型的超参数设置

### ISSUE THREAD

**Issue by syydhhd** [CCIIPLab/BiSyn_GAT_plus#1]
在使用给定的参数进行非MAMS数据集的训练时，模型并未达到理想的效果，请问能否提供训练这些数据集时的超参数和依赖库以及python版本以便我们进行结果的复现，感激不尽。

**Comment by Suda777** [comment]
我也是，复现不到论文中的结果。

**Comment by ShuoLiang-95** [comment]
可以参考以下超参数设置：
Restaurant:
lr=1e-5; bert_lr=2e-5; input_dropout=0.6; layer_dropout=0.4; batch_size=12; aspect_graph_num_layer=3; seed=376;

Laptop:
lr=1e-5; bert_lr=2e-5; input_dropout=0.2; layer_dropout=0.7; batch_size=12; aspect_graph_num_layer=2; attn_head=2; seed=120;

Twitter:
lr=2e-5; bert_lr=1e-5; input_dropout=0.4; layer_dropout=0.6; attn_dropout=0.5; num_encoder_layer=2; attn_head=4; batch_size=20; seed=173;

环境设置：
python=3.7; torch >= 1.7;  transformers >= 4.3.3

**Comment by ShuoLiang-98** [comment]
可以参考以下超参数设置：
Restaurant:
lr=1e-5; bert_lr=2e-5; input_dropout=0.6; layer_dropout=0.4; aspect_graph_num_layer=3;

Laptop:
lr=1e-5; bert_lr=2e-5; input_dropout=0.2; layer_dropout=0.7; aspect_graph_num_layer=2; attn_head=2;

Twitter:
lr=2e-5; bert_lr=1e-5; input_dropout=0.4; layer_dropout=0.6; attn_dropout=0.5; num_encoder_layer=2; attn_head=4;

环境设置：
python=3.7; torch >= 1.7; transformers >= 4.3.3
