### ISSUE TITLE
代码运行出错

### ISSUE THREAD

**Issue by Peng99999** [CCIIPLab/BiSyn_GAT_plus#2]
python3.6
Pytorch=1.2.0
Transformers 2.9.1
为啥运行时Epoch1后打印错误：
in forward
bert_out , bert_pooler_out = bert_outputs.last_hidden_state , bert_outputs.pooler_output
AttributeError:'tuple' obeject has no attribute 'last_hidden_state'

**Comment by HappyBoyss** [comment]
你好，transformers的2.9.1版本在哪里下载的 ？找了好久也没找到

**Comment by HappyBoyss** [comment]
您好，这个错误您解决了吗，我也遇到了这个错误

**Comment by ShuoLiang-98** [comment]
可能是因为transformers库版本太低，试一下transformers >= 4.3.3
