### ISSUE TITLE
运行代码出现这个错误，请问作者大大这个怎么解决呢，是什么原因呢？

### ISSUE THREAD

**Issue by motuomumu** [CCIIPLab/BiSyn_GAT_plus#7]
File "train.py", line 163, in run
    train_dataloader, valid_dataloader, test_dataloader = load_data(args, vocab, tokenizer)
TypeError: load_data() takes 1 positional argument but 3 were given

**Comment by YouAreAllINeed** [comment]
你改过代码没，我是可以直接运行的。从错误信息上看，load_data需要一个参数，但你给了三个，但是源代码确实是这样写的，你看有没有重名的load_data函数？
