### ISSUE TITLE
请问作者大大，项目文件中数据集部分都是处理过的数据，请问可以分享下未处理过的原始数据集嘛（相同划分标准）

### ISSUE THREAD

**Issue by JM0011** [CCIIPLab/BiSyn_GAT_plus#8]

**Comment by JM0011** [comment]
补充一个问题，为什么在代码中有区分验证集而论文中却未提及（其他ABSA论文好多也都是不区分验证集，好奇怪），希望作者大大能够解惑一下

**Comment by YouAreAllINeed** [comment]
其实你仔细看，验证集和测试集的数据是一样的。

**Comment by ShuoLiang-98** [comment]
数据集参考了：https://github.com/goodbai-nlp/RGAT-ABSA
